"""Export corrections: Equalizer APO / EasyEffects text, PipeWire filter-chain sink (local or on a
remote PipeWire box such as the Raspberry Pi that feeds the amplifier), plain table.

A correction set is:
  corrections: [{"type": "peaking", "freq_hz", "gain_db", "q", "reason"}, ...]   (applied to all channels)
  channel_ops: {"invert": ["1"], "delay_ms": {"0": 2.2}}                        (per channel, optional)
Channel "0" is left, "1" is right.
"""
import os
import shlex
import subprocess
import textwrap

PW_CONF_DIR = os.path.expanduser("~/.config/pipewire/pipewire.conf.d")
PW_CONF_NAME = "60-aaa-room-eq.conf"
PW_CONF_FILE = os.path.join(PW_CONF_DIR, PW_CONF_NAME)
EQ_SINK = "aaa_room_eq_sink"


def as_table(corr, channel_ops=None):
    lines = ["Type      Freq(Hz)  Gain(dB)   Q     Reason", "-" * 60]
    for c in corr:
        lines.append(f"{c['type']:<9} {c['freq_hz']:>8.1f} {c['gain_db']:>8.1f} {c['q']:>5.1f}   {c.get('reason','')}")
    ops = channel_ops or {}
    for ch in ops.get("invert", []):
        lines.append(f"invert    channel {ch} ({'left' if str(ch)=='0' else 'right'}) polarity")
    for ch, ms in (ops.get("delay_ms") or {}).items():
        if ms:
            lines.append(f"delay     channel {ch} ({'left' if str(ch)=='0' else 'right'}) by {ms:.2f} ms")
    return "\n".join(lines)


def as_apo(corr):
    """Equalizer APO format; importable by EasyEffects (Linux), Peace (Windows), eqMac (macOS).
    (Per-channel polarity/delay are not expressible here.)"""
    pre = min(0.0, -max((c["gain_db"] for c in corr if c["gain_db"] > 0), default=0.0))
    out = [f"Preamp: {pre:.1f} dB"]
    for i, c in enumerate(corr, 1):
        out.append(f"Filter {i}: ON PK Fc {c['freq_hz']:.1f} Hz Gain {c['gain_db']:.1f} dB Q {c['q']:.2f}")
    return "\n".join(out) + "\n"


def as_pipewire_conf(corr, target_sink, channel_ops=None, name="Room EQ", channels=("0", "1")):
    """Filter-chain with an independent path per channel: [invert] -> [delay] -> peaking EQs.
    Output goes to `target_sink` (node.name).  Select the new sink "Room EQ" as default output."""
    ops = channel_ops or {}
    nodes, links, ins, outs = [], [], [], []
    for ch in channels:
        chain = []
        if str(ch) in [str(x) for x in ops.get("invert", [])]:
            chain.append((f"inv{ch}", '{ type = builtin label = invert name = %s }' % f"inv{ch}"))
        d = (ops.get("delay_ms") or {}).get(str(ch), 0) or 0
        if d > 0:
            chain.append((f"dly{ch}", '{ type = builtin label = delay name = %s config = { "max-delay" = 1.0 } control = { "Delay (s)" = %.6f } }' % (f"dly{ch}", d / 1000.0)))
        for i, c in enumerate(corr):
            chain.append((f"eq{ch}_{i}", '{ type = builtin label = bq_peaking name = %s control = { "Freq" = %.1f "Q" = %.2f "Gain" = %.1f } }'
                          % (f"eq{ch}_{i}", c["freq_hz"], c["q"], c["gain_db"])))
        if not chain:
            chain.append((f"cp{ch}", '{ type = builtin label = copy name = %s }' % f"cp{ch}"))
        for j, (nm, txt) in enumerate(chain):
            nodes.append("          " + txt)
            if j:
                links.append(f'          {{ output = "{chain[j-1][0]}:Out" input = "{nm}:In" }}')
        ins.append(f'"{chain[0][0]}:In"')
        outs.append(f'"{chain[-1][0]}:Out"')
    pos = "[ FL FR ]" if len(channels) == 2 else "[ " + " ".join(f"AUX{i}" for i in range(len(channels))) + " ]"
    return textwrap.dedent(f"""\
        # Generated by auto_audio_assist.  Virtual sink "{name}" applying room corrections
        # (per-channel polarity / delay / parametric EQ), forwarding to {target_sink}.
        # Make it the default output:  wpctl set-default <id of {EQ_SINK}>
        context.modules = [
          {{ name = libpipewire-module-filter-chain
            args = {{
              node.description = "{name}"
              media.name = "{name}"
              filter.graph = {{
                nodes = [
        """) + "\n".join(nodes) + "\n        ]\n        links = [\n" + "\n".join(links) + textwrap.dedent(f"""

                ]
                inputs = [ {" ".join(ins)} ]
                outputs = [ {" ".join(outs)} ]
              }}
              capture.props = {{
                node.name = "{EQ_SINK}"
                media.class = Audio/Sink
                audio.channels = {len(channels)}
                audio.position = {pos}
              }}
              playback.props = {{
                node.name = "aaa_room_eq_output"
                node.passive = true
                target.object = "{target_sink}"
                audio.channels = {len(channels)}
                audio.position = {pos}
              }}
            }}
          }}
        ]
        """)


_RESTART = "systemctl --user restart pipewire pipewire-pulse wireplumber"
_SET_DEFAULT = ("for i in $(seq 40); do ID=$(pw-dump 2>/dev/null | python3 -c \"import json,sys\n"
                "for o in json.load(sys.stdin):\n  p=o.get('info',{}).get('props',{})\n"
                f"  if p.get('node.name')=='{EQ_SINK}': print(o['id'])\" | head -1); "
                "[ -n \"$ID\" ] && wpctl set-default $ID && echo default=$ID && exit 0; sleep 0.5; done; "
                "echo 'EQ sink did not appear' >&2; exit 1")


def install_pipewire(corr, target_sink, channel_ops=None, restart=True, set_default=True):
    """Install the EQ sink on THIS machine."""
    os.makedirs(PW_CONF_DIR, exist_ok=True)
    with open(PW_CONF_FILE, "w") as f:
        f.write(as_pipewire_conf(corr, target_sink, channel_ops))
    if restart:
        subprocess.run(_RESTART, shell=True, check=False)
        if set_default:
            subprocess.run(_SET_DEFAULT, shell=True, check=False)
    return PW_CONF_FILE


def uninstall_pipewire(restart=True):
    if os.path.exists(PW_CONF_FILE):
        os.remove(PW_CONF_FILE)
        if restart:
            subprocess.run(_RESTART, shell=True, check=False)
        return True
    return False


def install_pipewire_remote(host, corr, target_sink, channel_ops=None, set_default=True, timeout=90):
    """Install the EQ sink on a remote PipeWire box over ssh (e.g. the Pi feeding the amp).
    Writes ~/.config/pipewire/pipewire.conf.d/60-aaa-room-eq.conf there, restarts the user PipeWire
    services and makes the EQ sink the default so Bluetooth (bluealsa-aplay --pcm=pipewire),
    Spotify Connect (librespot) and anything else routed to the default sink gets corrected."""
    conf = as_pipewire_conf(corr, target_sink, channel_ops)
    script = (f"mkdir -p ~/.config/pipewire/pipewire.conf.d && cat > ~/.config/pipewire/pipewire.conf.d/{PW_CONF_NAME} "
              f"&& {_RESTART} && sleep 2" + (f" && {_SET_DEFAULT}" if set_default else "") +
              " && wpctl status | sed -n '/Sinks:/,/Sources:/p'")
    r = subprocess.run(["ssh", "-o", "BatchMode=yes", "-o", "ConnectTimeout=10", host, script],
                       input=conf, capture_output=True, text=True, timeout=timeout)
    if r.returncode != 0:
        raise RuntimeError(f"remote install failed ({r.returncode}): {r.stderr[-800:]}")
    return r.stdout


def uninstall_pipewire_remote(host, restore_default=None, timeout=90):
    script = f"rm -f ~/.config/pipewire/pipewire.conf.d/{PW_CONF_NAME} && {_RESTART} && sleep 2"
    if restore_default:
        script += (f" && ID=$(pw-dump | python3 -c \"import json,sys\nfor o in json.load(sys.stdin):\n  p=o.get('info',{{}}).get('props',{{}})\n"
                   f"  if p.get('node.name')=='{restore_default}': print(o['id'])\" | head -1) && wpctl set-default $ID")
    r = subprocess.run(["ssh", "-o", "BatchMode=yes", host, script], capture_output=True, text=True, timeout=timeout)
    if r.returncode != 0:
        raise RuntimeError(f"remote uninstall failed ({r.returncode}): {r.stderr[-800:]}")
    return r.stdout
