"""Export corrections: Equalizer APO / EasyEffects text, PipeWire filter-chain sink, plain table."""
import os
import subprocess
import textwrap

PW_CONF_DIR = os.path.expanduser("~/.config/pipewire/pipewire.conf.d")
PW_CONF_FILE = os.path.join(PW_CONF_DIR, "60-aaa-room-eq.conf")


def as_table(corr):
    lines = ["Type      Freq(Hz)  Gain(dB)   Q     Reason", "-" * 60]
    for c in corr:
        lines.append(f"{c['type']:<9} {c['freq_hz']:>8.1f} {c['gain_db']:>8.1f} {c['q']:>5.1f}   {c.get('reason','')}")
    return "\n".join(lines)


def as_apo(corr):
    """Equalizer APO format; importable by EasyEffects (Linux), Peace (Windows), eqMac (macOS)."""
    pre = min(0.0, -max((c["gain_db"] for c in corr if c["gain_db"] > 0), default=0.0))
    out = [f"Preamp: {pre:.1f} dB"]
    for i, c in enumerate(corr, 1):
        out.append(f"Filter {i}: ON PK Fc {c['freq_hz']:.1f} Hz Gain {c['gain_db']:.1f} dB Q {c['q']:.2f}")
    return "\n".join(out) + "\n"


def as_pipewire_conf(corr, target_sink, name="Room EQ"):
    nodes, links = [], []
    for i, c in enumerate(corr):
        nodes.append(textwrap.dedent(f"""\
                    {{ type = builtin label = bq_peaking name = eq{i}
                      control = {{ "Freq" = {c['freq_hz']:.1f} "Q" = {c['q']:.2f} "Gain" = {c['gain_db']:.1f} }} }}"""))
        if i:
            links.append(f'                    {{ output = "eq{i-1}:Out" input = "eq{i}:In" }}')
    if not nodes:
        nodes.append('                    { type = builtin label = copy name = eq0 }')
    last = len(corr) - 1 if corr else 0
    return textwrap.dedent(f"""\
        # Generated by auto_audio_assist.  Creates a virtual sink "{name}" that applies the room
        # corrections and forwards to {target_sink}.  Select "{name}" as your output device.
        context.modules = [
          {{ name = libpipewire-module-filter-chain
            args = {{
              node.description = "{name}"
              media.name = "{name}"
              filter.graph = {{
                nodes = [
        """) + "\n".join(nodes) + textwrap.dedent(f"""

                ]
                links = [
        """) + "\n".join(links) + textwrap.dedent(f"""

                ]
                inputs = [ "eq0:In" ]
                outputs = [ "eq{last}:Out" ]
              }}
              capture.props = {{
                node.name = "aaa_room_eq_sink"
                media.class = Audio/Sink
                audio.channels = 2
                audio.position = [ FL FR ]
              }}
              playback.props = {{
                node.name = "aaa_room_eq_output"
                node.passive = true
                target.object = "{target_sink}"
                audio.channels = 2
                audio.position = [ FL FR ]
              }}
            }}
          }}
        ]
        """)


def install_pipewire(corr, target_sink, restart=True):
    os.makedirs(PW_CONF_DIR, exist_ok=True)
    with open(PW_CONF_FILE, "w") as f:
        f.write(as_pipewire_conf(corr, target_sink))
    if restart:
        subprocess.run(["systemctl", "--user", "restart", "pipewire", "pipewire-pulse", "wireplumber"], check=False)
    return PW_CONF_FILE


def uninstall_pipewire(restart=True):
    if os.path.exists(PW_CONF_FILE):
        os.remove(PW_CONF_FILE)
        if restart:
            subprocess.run(["systemctl", "--user", "restart", "pipewire", "pipewire-pulse", "wireplumber"], check=False)
        return True
    return False
